# this stub is created to allow the reconciler to track this/these resource(s). It should not be deleted. The actual content of this resource and managed and reconciled by the function-webhook.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: warden-webhook