apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: admission
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          imagePullPolicy: IfNotPresent
          image: "{{ .Values.global.admission.image }}"
          args:
            - --config-path={{- .Values.global.config.dir }}/{{- .Values.global.config.filename }}
          ports:
            - name: https-admission
              containerPort: 8443
            - name: http-metrics
              containerPort: 9090
            - name: http-profiling
              containerPort: 8008
          volumeMounts:
            - name: config
              mountPath: {{ .Values.global.config.dir }}
            - name: certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
      volumes:
        - name: config
          configMap:
            name: {{ .Values.global.config.configmapName }}
        - name: certs
          secret:
            secretName: {{ .Chart.Name }}-cert

