apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: webhook
          imagePullPolicy: IfNotPresent
          image: {{ .Values.global.webhook.image }}
          ports:
            - name: https-webhook
              containerPort: 8443
            - name: http-metrics
              containerPort: 9090
            - name: http-profiling
              containerPort: 8008
          volumeMounts:
            - name: serverless-webhook
              mountPath: /tmp/k8s-webhook-server/serving-certs
      volumes:
        - name: serverless-webhook
          secret:
            secretName: {{ .Chart.Name }}

