apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https-admission
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: {{ .Chart.Name }}
