apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.config.configmapName }}
  namespace: {{ .Release.Namespace }}
data: |
  {{ .Values.global.config.filename }}: {{ toYaml .Values.global.config.data | quote  }}
