apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.config.configmapName }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.global.config.filename }}: {{ tpl ( toYaml .Values.global.config.data ) . | quote  }}
