# permissions for end users to edit imagepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: imagepolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: warden
    app.kubernetes.io/part-of: warden
    app.kubernetes.io/managed-by: kustomize
  name: imagepolicy-editor-role
rules:
- apiGroups:
  - validate.warden.kyma-project.io
  resources:
  - imagepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validate.warden.kyma-project.io
  resources:
  - imagepolicies/status
  verbs:
  - get
