---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - patch
  - update
  - watch
- apiGroups:
  - validate.warden.kyma-project.io
  resources:
  - imagepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validate.warden.kyma-project.io
  resources:
  - imagepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - validate.warden.kyma-project.io
  resources:
  - imagepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - validate.warden.kyma-project.io
  resources:
  - validators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validate.warden.kyma-project.io
  resources:
  - validators/finalizers
  verbs:
  - update
- apiGroups:
  - validate.warden.kyma-project.io
  resources:
  - validators/status
  verbs:
  - get
  - patch
  - update
