apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.global.name }}
    app.kubernetes.io/name: {{ .Values.global.name }}
    app.kubernetes.io/component: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app: {{ .Values.global.name }}
    app.kubernetes.io/name: {{ .Values.global.name }}
    app.kubernetes.io/component: {{ .Chart.Name }}